module.exports = {
  tags: [
    'b',
    'i',
    'u',
    's',
    'color',
    'size',
    'font',
    'img',
    'url',
    'picon',
    'ulist',
    'list',
    'li',
    'block',
    'toggle',
    'table',
    'tr',
    'td',
    'th',
  ],

  pairedTags: [
    'b',
    'i',
    'u',
    's',
    'color',
    'size',
    'font',
    'img',
    'url',
    'picon',
    'ulist',
    'list',
    'li',
    'block',
    'table',
    'tr',
    'td',
    'th',
  ],

  implicitValueTags: {
    block: [
      'panel',
      'panelheader',
      'hidden',
      'blackborder',
      'white',
      'pad5',
      'pad10',
      'center',
      'right',
      'automargin',
      'floatcontainer',
      'floatleft',
      'floatright',
      'tooltip',
    ],
    table: ['automargin'],
    size: ['8', '10', '12', '14', '16', '18'],
  },

  freeformImplicitValueTags: ['size', 'color', 'font', 'url', 'img'],

  bareBlockTokens: [
    'panel',
    'panelheader',
    'hidden',
    'blackborder',
    'white',
    'pad5',
    'pad10',
    'center',
    'right',
    'automargin',
    'floatcontainer',
    'floatleft',
    'floatright',
    'tooltip',
    'border2',
    'blue',
    'black',
    'yellowbg',
    'whitebg',
  ],

  attributesByTag: {
    block: [
      'display',
      'bg',
      'fg',
      'bgi',
      'width',
      'height',
      'position',
      'top',
      'left',
      'id',
      'group',
      'tooltip',
      'border',
      'colspan',
      'rowspan',
      'valign',
    ],
    toggle: ['label', 'block', 'group', 'width'],
    table: [
      'width',
      'bg',
      'fg',
      'bgi',
      'border',
      'colspan',
      'rowspan',
      'valign',
    ],
    td: ['width', 'bg', 'fg', 'bgi', 'border', 'colspan', 'rowspan', 'valign'],
    th: ['width', 'bg', 'fg', 'bgi', 'border', 'colspan', 'rowspan', 'valign'],
  },
};
